### ISSUE TITLE
Take name in more than one language

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance#21] opened 2019-03-31 17:40 UTC
Allow the user to save name in more than one language and let admin see all names in his exported sheet.

**Comment by 0crat** [comment] 2019-03-31 17:45
Job [#21](https://github.com/ammaratef45/attendance/issues/21) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-03-31 17:51
The job [#21](https://github.com/ammaratef45/attendance/issues/21) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/ef9681cc-634d-40dd-859f-9115010662c1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-03-31 17:52
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment] 2019-04-01 22:40
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) I see that you unassigned this issue; the order is still assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by ammaratef45** [comment] 2019-04-01 22:42
@0crat assign @Bahaaib

**Comment by 0crat** [comment] 2019-04-01 22:46
The job [#21](https://github.com/ammaratef45/attendance/issues/21) assigned to @bahaaib[/z](https://www.0crat.com/u/bahaaib), here is [why](https://www.0crat.com/footprint/CH951175M/88622635-ebc7-4830-82cf-71c1c336cf00); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @bahaaib[/z](https://www.0crat.com/u/bahaaib) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-04-01 22:47
> @0crat assign @Bahaaib ([here](https://github.com/ammaratef45/Attendance/issues/21#issuecomment-478773534))

@ammaratef45 Job [#21](https://github.com/ammaratef45/attendance/issues/21) is already assigned to @bahaaib[/z](https://www.0crat.com/u/bahaaib)

**Comment by 0crat** [comment] 2019-04-01 22:48
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment] 2019-04-06 16:41
@ammaratef45 2 puzzles [#24](https://github.com/ammaratef45/Attendance/issues/24), [#25](https://github.com/ammaratef45/Attendance/issues/25) are still not solved.

**Closed** 2019-04-06 17:27 UTC
Labels: scope

**Comment by 0crat** [comment] 2019-04-06 17:46
Job [#21](https://github.com/ammaratef45/attendance/issues/21) is not in the agenda of @bahaaib[/z](https://www.0crat.com/u/bahaaib), can't retrieve data and time of add

**Comment by 0crat** [comment] 2019-04-06 17:46
@bahaaib[/z](https://www.0crat.com/u/bahaaib) the issue is closed not by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) (its creator); I won't close the order; please, re-open it and ask @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) to close it

**Comment by 0crat** [comment] 2019-04-06 23:40
@bahaaib[/z](https://www.0crat.com/u/bahaaib) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment] 2019-04-07 10:26
@0crat out

**Comment by ammaratef45** [comment] 2019-04-07 10:26
@Bahaaib Thanks :+1:

**Comment by 0crat** [comment] 2019-04-07 10:26
> @0crat out ([here](https://github.com/ammaratef45/Attendance/issues/21#issuecomment-480577750))

@ammaratef45 Job [#21](https://github.com/ammaratef45/attendance/issues/21) is not in the agenda of @bahaaib[/z](https://www.0crat.com/u/bahaaib), can't retrieve data and time of add

**Comment by 0crat** [comment] 2019-04-07 10:31
> @0crat out ([here](https://github.com/ammaratef45/Attendance/issues/21#issuecomment-480577750))

@ammaratef45 The job [#21](https://github.com/ammaratef45/attendance/issues/21) is now out of scope

**Comment by 0crat** [comment] 2019-04-07 10:33
Order was finished: +30 point(s) just awarded to @bahaaib[/z](https://www.0crat.com/u/bahaaib)

**Comment by 0pdd** [comment] 2019-04-08 04:16
@ammaratef45 the puzzle [#26](https://github.com/ammaratef45/Attendance/issues/26) is still not solved; solved: [#24](https://github.com/ammaratef45/Attendance/issues/24), [#25](https://github.com/ammaratef45/Attendance/issues/25).

**Comment by 0pdd** [comment] 2019-04-13 00:58
@ammaratef45 5 puzzles [#37](https://github.com/ammaratef45/Attendance/issues/37), [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39), [#40](https://github.com/ammaratef45/Attendance/issues/40), [#41](https://github.com/ammaratef45/Attendance/issues/41) are still not solved; solved: [#24](https://github.com/ammaratef45/Attendance/issues/24), [#25](https://github.com/ammaratef45/Attendance/issues/25), [#26](https://github.com/ammaratef45/Attendance/issues/26).

**Comment by 0pdd** [comment] 2019-04-14 09:53
@ammaratef45 4 puzzles [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39), [#40](https://github.com/ammaratef45/Attendance/issues/40), [#41](https://github.com/ammaratef45/Attendance/issues/41) are still not solved; solved: [#24](https://github.com/ammaratef45/Attendance/issues/24), [#25](https://github.com/ammaratef45/Attendance/issues/25), [#26](https://github.com/ammaratef45/Attendance/issues/26), [#37](https://github.com/ammaratef45/Attendance/issues/37).

**Comment by 0pdd** [comment] 2019-04-16 11:39
@ammaratef45 2 puzzles [#40](https://github.com/ammaratef45/Attendance/issues/40), [#41](https://github.com/ammaratef45/Attendance/issues/41) are still not solved; solved: [#24](https://github.com/ammaratef45/Attendance/issues/24), [#25](https://github.com/ammaratef45/Attendance/issues/25), [#26](https://github.com/ammaratef45/Attendance/issues/26), [#37](https://github.com/ammaratef45/Attendance/issues/37), [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39).

**Comment by 0pdd** [comment] 2019-04-24 17:43
@ammaratef45 2 puzzles [#40](https://github.com/ammaratef45/Attendance/issues/40), [#54](https://github.com/ammaratef45/Attendance/issues/54) are still not solved; solved: [#24](https://github.com/ammaratef45/Attendance/issues/24), [#25](https://github.com/ammaratef45/Attendance/issues/25), [#26](https://github.com/ammaratef45/Attendance/issues/26), [#37](https://github.com/ammaratef45/Attendance/issues/37), [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39), [#41](https://github.com/ammaratef45/Attendance/issues/41).

**Comment by 0pdd** [comment] 2019-04-26 15:24
@ammaratef45 the puzzle [#40](https://github.com/ammaratef45/Attendance/issues/40) is still not solved; solved: [#24](https://github.com/ammaratef45/Attendance/issues/24), [#25](https://github.com/ammaratef45/Attendance/issues/25), [#26](https://github.com/ammaratef45/Attendance/issues/26), [#37](https://github.com/ammaratef45/Attendance/issues/37), [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39), [#41](https://github.com/ammaratef45/Attendance/issues/41), [#54](https://github.com/ammaratef45/Attendance/issues/54).
