### ISSUE TITLE
Write unit tests to test the user class

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance#27] opened 2019-04-08 13:41 UTC
In `backend/user.dart` a class called user that holds the data of the user
We need some unit tests to test its instantiation, member functions, getters and setters.

**Comment by 0crat** [comment] 2019-04-08 13:45
The job [#27](https://github.com/ammaratef45/attendance/issues/27) assigned to @bahaaib[/z](https://www.0crat.com/u/bahaaib), here is [why](https://www.0crat.com/footprint/CH951175M/02a7b135-5d0f-4b8a-8278-b6da8721088c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @bahaaib[/z](https://www.0crat.com/u/bahaaib) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-04-08 13:52
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment] 2019-04-08 13:53
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment] 2019-04-11 12:19
@bahaaib[/z](https://www.0crat.com/u/bahaaib) the issue is closed not by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) (its creator); I won't close the order; please, re-open it and ask @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) to close it

**Closed** 2019-04-11 13:36 UTC
Labels: scope

**Comment by 0crat** [comment] 2019-04-11 14:07
Order was finished: +30 point(s) just awarded to @bahaaib[/z](https://www.0crat.com/u/bahaaib)

**Comment by 0crat** [comment] 2019-04-11 14:08
The job [#27](https://github.com/ammaratef45/attendance/issues/27) is now out of scope
